---
- hosts: my_servers
  become: true

  tasks:
    - name: Install apache2
      apt: name=apache2 update_cache=no state=latest
      

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
