---
- hosts: ubuntu_vm
  become: yes
  vars:
    wp_db_name: wordpress1
    wp_db_user: wordpress
    wp_db_password: secure-123
    db_host: 44.210.103.164  # Added db_host
    table_prefix: wp_

  tasks:
  - name: Update APT package cache
    apt:
      update_cache: yes

  - name: Install LAMP stack
    apt:
      name:
        - apache2
        - mysql-server
        - php
        - libapache2-mod-php
        - php-mysql
        - python3-pymysql
      state: present

  - name: Start Apache and MySQL services
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - apache2
      - mysql

  - name: Remove MySQL root password
    shell: |
      mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
      mysql -u root -e "FLUSH PRIVILEGES;"

  - name: Create a new database for WordPress
    mysql_db:
      name: "{{ wp_db_name }}"
      state: present
      login_user: root
      login_password: ""

  - name: Create a new user for WordPress
    mysql_user:
      name: "{{ wp_db_user }}"
      password: "{{ wp_db_password }}"
      priv: "*.*:ALL"
      host: "%"
      state: present
    notify: restart mysql

  - name: Download WordPress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/wordpress.tar.gz
      mode: '0644'

  - name: Extract WordPress
    unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /var/www/html/
      remote_src: yes

  - name: Update WordPress config file
    template:
      src: ./ubuntu-wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php

  - name: Restart Apache service
    systemd:
      name: apache2
      state: restarted

  handlers:
    - name: restart mysql
      systemd:
        name: mysql
        state: restarted
